language: cpp
sudo: required
dist: trusty

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis-linux.sh; fi

deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  draft: true
  prerelease: true
  api_key:
    secure: ""
  file: "ETe*.7z"
  on:
    tags: true

notifications:
  email: false
